In [1]:
import pandas as pd
import os

In [2]:
folder = r'D:\Study\Data Engineering and Analytics\Data Engineering with Pandas - Udemy\Data+Science+in+Python+-+Data+Prep+&+EDA\Data'

In [3]:
os.listdir(folder)

['.ipynb_checkpoints',
 'Alarm Survey Data.xlsx',
 'Book_Customers.csv',
 'Book_Sales_April.xlsx',
 'Book_Sales_June.xlsx',
 'Book_Sales_May.xlsx',
 'Course Offerings.xlsx',
 'course_offerings.csv',
 'Groceries.xlsx',
 'groceries_with_new_columns.pkl',
 'happiness_data_ca.txt',
 'happiness_data_cr.txt',
 'happiness_data_mx.txt',
 'happiness_data_us.txt',
 'happiness_survey_data.csv',
 'house_listings.csv',
 'maven.db',
 'maven_music_customers.csv',
 'maven_music_listening_history.xlsx',
 'online_shop.db',
 'Pen Sales Data.xlsx',
 'Rotten Tomatoes Movies.csv',
 'Run Times.xlsx',
 'Sales Tables.xlsx',
 'spotify_songs.csv',
 'Student Grades.xlsx',
 'student_data.csv']

In [4]:
#Read from a csv file
course_offerings_csv = pd.read_csv(folder + '/course_offerings.csv')

In [5]:
course_offerings_csv

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [6]:
#Read from an excel file
course_offerings_excel = pd.read_excel(folder + '/Course Offerings.xlsx')

In [7]:
course_offerings_excel

     Instructor                    Title
0  Chris Bruehl   Lead Python Instructor
1   John Pauler     Chief Growth Officer
2    Alice Zhao  Data Science Instructor

In [8]:
#Read from the second sheet of excel, starts from 0
course_offerings_excel = pd.read_excel(folder + '/Course Offerings.xlsx', sheet_name = 1)

In [9]:
course_offerings_excel

   Course ID                  Course Name    Instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [10]:
#Connect to an SQL Database

In [11]:
#Specific library for PostgreSQL
import psycopg2

In [12]:
postgre_conn = psycopg2.connect(dbname = 'dvdrental', user = 'postgres', password = 'Letmein555', port = 5433, host = 'localhost')

In [13]:
postgre_actor = pd.read_sql('SELECT * FROM Actor', postgre_conn)

C:\Users\shlom\AppData\Local\Temp\ipykernel_15440\349700997.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  postgre_actor = pd.read_sql('SELECT * FROM Actor', postgre_conn)

In [14]:
postgre_actor

     actor_id first_name     last_name             last_update
0           1   Penelope       Guiness 2013-05-26 14:47:57.620
1           2       Nick      Wahlberg 2013-05-26 14:47:57.620
2           3         Ed         Chase 2013-05-26 14:47:57.620
3           4   Jennifer         Davis 2013-05-26 14:47:57.620
4           5     Johnny  Lollobrigida 2013-05-26 14:47:57.620
..        ...        ...           ...                     ...
195       196       Bela        Walken 2013-05-26 14:47:57.620
196       197      Reese          West 2013-05-26 14:47:57.620
197       198       Mary        Keitel 2013-05-26 14:47:57.620
198       199      Julia       Fawcett 2013-05-26 14:47:57.620
199       200      Thora        Temple 2013-05-26 14:47:57.620

[200 rows x 4 columns]